<a href="https://colab.research.google.com/github/BrendaCopatti/pattern_recognition/blob/main/decision_trees.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Brenda Sabrina Copatti**
## Introdução ao Reconhecimento de Padrões (2021-1)
### 28/11 - Atividade - Decision Trees

### **Importando as bibliotecas**

In [190]:
from sklearn.datasets import load_breast_cancer
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from sklearn.neighbors import KNeighborsClassifier
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import GridSearchCV
from sklearn.tree import plot_tree
import numpy as np
import pandas as pd

### **Leitura do dataset**

In [191]:
data = load_breast_cancer()
df = pd.DataFrame(data.data, columns = data.feature_names)
df['target'] = data.target
df.head()

mean radius  mean texture  ...  worst fractal dimension  target
0        17.99         10.38  ...                  0.11890       0
1        20.57         17.77  ...                  0.08902       0
2        19.69         21.25  ...                  0.08758       0
3        11.42         20.38  ...                  0.17300       0
4        20.29         14.34  ...                  0.07678       0

[5 rows x 31 columns]

### **Manipulando os dados**

In [192]:
y = df['target'].values
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [193]:
X = df.iloc[:, 0:29].values
X

array([[ 17.99  ,  10.38  , 122.8   , ...,   0.7119,   0.2654,   0.4601],
       [ 20.57  ,  17.77  , 132.9   , ...,   0.2416,   0.186 ,   0.275 ],
       [ 19.69  ,  21.25  , 130.    , ...,   0.4504,   0.243 ,   0.3613],
       ...,
       [ 16.6   ,  28.08  , 108.3   , ...,   0.3403,   0.1418,   0.2218],
       [ 20.6   ,  29.33  , 140.1   , ...,   0.9387,   0.265 ,   0.4087],
       [  7.76  ,  24.54  ,  47.92  , ...,   0.    ,   0.    ,   0.2871]])

In [194]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=123, stratify=y)

In [195]:
print('Labels count in y', np.bincount(y))
print('Labels count in y_train', np.bincount(y_train))
print('Labels count in y_test', np.bincount(y_test))

Labels count in y [212 357]
Labels count in y_train [170 285]
Labels count in y_test [42 72]


### **Criando pipeline**

In [196]:
pipe = Pipeline([
                 ('z-score', StandardScaler()),
                 ('reduce_dim', PCA(n_components=2)),
                 ('classify', DecisionTreeClassifier())
])

### **Realizando GridSearch**

In [197]:
param_grid = {
    'reduce_dim__n_components': [1, 2, 3, 4],
    'classify__random_state': [2, 3, 4, 5, 6, 7],
}

grid = GridSearchCV(pipe, cv=2, n_jobs=1, param_grid=param_grid, scoring='accuracy')

In [198]:
grid.fit(X_train, y_train)

GridSearchCV(cv=2,
             estimator=Pipeline(steps=[('z-score', StandardScaler()),
                                       ('reduce_dim', PCA(n_components=2)),
                                       ('classify', DecisionTreeClassifier())]),
             n_jobs=1,
             param_grid={'classify__random_state': [2, 3, 4, 5, 6, 7],
                         'reduce_dim__n_components': [1, 2, 3, 4]},
             scoring='accuracy')

Verificando média de score obtido

In [199]:
grid.cv_results_['mean_test_score']

array([0.89670763, 0.9208401 , 0.91203918, 0.92080145, 0.89670763,
       0.92083044, 0.91645413, 0.90106461, 0.89670763, 0.91205851,
       0.90985586, 0.90544092, 0.89670763, 0.91205851, 0.91426115,
       0.90105495, 0.89670763, 0.91426115, 0.91203918, 0.90326725,
       0.89670763, 0.92740938, 0.91641549, 0.91859881])

Verificando melhor score e melhores parâmetros

In [200]:
print(grid.best_score_)
print(grid.best_params_)

0.9274093824870546
{'classify__random_state': 7, 'reduce_dim__n_components': 2}


Atribuindo o melhor classificador encontrado e realizando predição

In [201]:
classifier=grid.best_estimator_
y_test_pred=classifier.predict(X_test)

Analise arvore de decisão


> Comentei essa parte pois estava ocorrendo um problema que eu não consegui resolver, acredito que está faltando um parâmetro no pipeline, mas eu não consegui identificar qual
Mensagem de erro
'Pipeline' object has no attribute 'tree_'






In [202]:
#plt.figure(figsize=(20,20))

#plot_tree(classifier, filled=True, rounded=True, class_names=df.columns)

Realizando teste com um dado de amostra da base selecionado

In [203]:
print(np.shape(X_test))
print(np.shape(y_test))

X_test1 = X_test[1,:]
y_test1 = y_test[1]

print(np.shape(X_test1))
print(np.shape(y_test1))

X_test1 = np.reshape(X_test1,(1,-1))
y_test1 = np.reshape(y_test1,(1))

print(np.shape(X_test1))
print(np.shape(y_test1))

(114, 29)
(114,)
(29,)
()
(1, 29)
(1,)


In [204]:
y_test1_pred = new_classifier.predict(X_test1)

y_test1_pred

array([0])

In [205]:
accuracy_score(y_test1, y_test1_pred)

1.0

In [206]:
X_test1

array([[1.969e+01, 2.125e+01, 1.300e+02, 1.203e+03, 1.096e-01, 1.599e-01,
        1.974e-01, 1.279e-01, 2.069e-01, 5.999e-02, 7.456e-01, 7.869e-01,
        4.585e+00, 9.403e+01, 6.150e-03, 4.006e-02, 3.832e-02, 2.058e-02,
        2.250e-02, 4.571e-03, 2.357e+01, 2.553e+01, 1.525e+02, 1.709e+03,
        1.444e-01, 4.245e-01, 4.504e-01, 2.430e-01, 3.613e-01]])