<a href="https://colab.research.google.com/github/BrendaCopatti/pattern_recognition/blob/main/grid_search.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Brenda Sabrina Copatti**
## Introdução ao Reconhecimento de Padrões (2021-1)
### 28/11 - Atividade - GridSearch

### **Importando as bibliotecas**

In [85]:
from sklearn.datasets import load_breast_cancer
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.pipeline import Pipeline
from sklearn.decomposition import PCA
from sklearn.model_selection import GridSearchCV
import numpy as np
import pandas as pd

### **Leitura do dataset**

In [86]:
data = load_breast_cancer()
df = pd.DataFrame(data.data, columns = data.feature_names)
df['target'] = data.target
df.head()

mean radius  mean texture  ...  worst fractal dimension  target
0        17.99         10.38  ...                  0.11890       0
1        20.57         17.77  ...                  0.08902       0
2        19.69         21.25  ...                  0.08758       0
3        11.42         20.38  ...                  0.17300       0
4        20.29         14.34  ...                  0.07678       0

[5 rows x 31 columns]

### **Manipulação dos dados**

In [87]:
df['target'].unique()

array([0, 1])

In [88]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype  
---  ------                   --------------  -----  
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         5

In [89]:
y = df['target'].values
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
       1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
       1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
       1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
       0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
       1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
       0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
       1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
       1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0,

In [90]:
X = df.iloc[:, 0:29].values
X

array([[ 17.99  ,  10.38  , 122.8   , ...,   0.7119,   0.2654,   0.4601],
       [ 20.57  ,  17.77  , 132.9   , ...,   0.2416,   0.186 ,   0.275 ],
       [ 19.69  ,  21.25  , 130.    , ...,   0.4504,   0.243 ,   0.3613],
       ...,
       [ 16.6   ,  28.08  , 108.3   , ...,   0.3403,   0.1418,   0.2218],
       [ 20.6   ,  29.33  , 140.1   , ...,   0.9387,   0.265 ,   0.4087],
       [  7.76  ,  24.54  ,  47.92  , ...,   0.    ,   0.    ,   0.2871]])

In [91]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, shuffle=True, random_state=1, stratify=y)

### **Realizando treinamento com parâmetros aleatorios manualmente**

Criação do pipeline

In [92]:
pipe = Pipeline([
                 ('z-score', StandardScaler()),
                 ('reduce_dim', PCA(n_components=2)),
                 ('classify', KNeighborsClassifier(n_neighbors=1))
])

Treinamento

In [93]:
pipe.fit(X_train, y_train)

Pipeline(steps=[('z-score', StandardScaler()),
                ('reduce_dim', PCA(n_components=2)),
                ('classify', KNeighborsClassifier(n_neighbors=1))])

Verificando score

In [94]:
y_test_pred = pipe.predict(X_test)
accuracy_score(y_test, y_test_pred)

0.9473684210526315

### **Realizando GridSearch para a busca dos melhores hiperparâmetros**

Criação

In [95]:
param_grid = {
    'reduce_dim__n_components': [1, 2, 3, 4],
    'classify__n_neighbors': [2, 3, 4, 5, 6, 7]
}

grid = GridSearchCV(pipe, cv=2, n_jobs=1, param_grid=param_grid, scoring='accuracy')

Treinamento

In [96]:
grid.fit(X_train, y_train)

GridSearchCV(cv=2,
             estimator=Pipeline(steps=[('z-score', StandardScaler()),
                                       ('reduce_dim', PCA(n_components=2)),
                                       ('classify',
                                        KNeighborsClassifier(n_neighbors=1))]),
             n_jobs=1,
             param_grid={'classify__n_neighbors': [2, 3, 4, 5, 6, 7],
                         'reduce_dim__n_components': [1, 2, 3, 4]},
             scoring='accuracy')

Verificando scores obtidos

In [97]:
grid.cv_results_['mean_test_score']

array([0.85939794, 0.91871474, 0.92747701, 0.92966033, 0.89236031,
       0.92750599, 0.9208884 , 0.94066388, 0.89676559, 0.92967965,
       0.92744803, 0.93626826, 0.89898756, 0.93628758, 0.92743836,
       0.94944547, 0.89457261, 0.9384709 , 0.92963135, 0.94504985,
       0.90993315, 0.93629724, 0.93184365, 0.94065422])

Verificando melho score e melhores parâmetros

In [98]:
print(grid.best_score_)
print(grid.best_params_)

0.9494454749207821
{'classify__n_neighbors': 5, 'reduce_dim__n_components': 4}


utilizando melhor classificador obtido

In [99]:
new_classifier=grid.best_estimator_
y_test_pred=new_classifier.predict(X_test)

Verificando score

In [100]:
accuracy_score(y_test, y_test_pred)

0.9649122807017544